# 一. 乘法符号
    1. 原始乘法运算
    2. 包重载符号
    3. 重载乘法符号，对应算法__mul__

In [2]:
# 基础乘法
7 * 8

56

In [3]:
# 基础乘方 2^3 = 8
2**3

8

In [2]:
# numpy中的乘法
import numpy as np
a = np.array([1,2,3])
b = np.array([10, 10, 10])
print("a:", a)
print("b:", b)
print("a * b =", a * b)

a: [1 2 3]
b: [10 10 10]
a * b = [10 20 30]


In [3]:
# numpy array所有的方法/变量属性
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [4]:
# 重载运算符号（类似于C++）
class square:
    def __init__(self, edge):
        self.edge = edge
    # 假设“*”表示两个rectangle构成的立方体体积
    def __mul__(self, square2):
        return self.edge * square2.edge

my_num = square(7)
# 已知正方形，求对应的立方体体积
print("重载 * 符号\t:", my_num * my_num)
print("等价于    \t:", my_num.__mul__(my_num))

重载 * 符号	: 49
等价于    	: 49


# 二. 引入包/文件（Packages/Module）的全部内容（不推荐）
1. ```from numpy import *```  (不推荐)

In [5]:
a = np.array([1,2,3])
b = np.array([10, 10, 10])

In [6]:
# 引入一个文件
from module_a import *  # 引入numpy中所有的方法/属性
print("外积")
print(array_prod(a, b))  # 外积
from module_b import *  # 引入numpy中所有的方法/属性
print("内积（外积方法被覆盖）")
print(array_prod(a, b))  # 内积

[[10 10 10]
 [20 20 20]
 [30 30 30]]
60


In [7]:
# 正确的使用方法
import module_a as ma
import module_b as mb
print("外积")
print(ma.array_prod(a, b))  # 外积
print("内积（外积方法不会被覆盖）")
print(mb.array_prod(a, b))  # 内积

外积
[[10 10 10]
 [20 20 20]
 [30 30 30]]
内积（外积方法不会被覆盖）
60


# 三.作为list/dictionary的迭代解构器（*/**）
    1. 配合zip重新组合list/tuple
    2. 作为函数(function)的动态参数传递方法
        2.1 (*) 用作按照位置顺序的参数输入 (use list for positional arguments)
        2.2（**）按照函数名传递参数（use dictionary for key-value arguments）
        2.3 实际项目中的使用方法

In [16]:
a = (1, 2, 3)
b = ['a', 'b', 'c']
print(*a)  # *的作用是按照顺序迭代数据结构（list/tuple/set/dict）

1 2 3


In [26]:
# 1. zip可以将两个同样程度的list/tuple这样的数据结构
# 按照位置依次组合在一起（想象拉链的结合方式）
c = list(zip(a, b))
print(c)

[(1, 'a'), (2, 'b'), (3, 'c')]


In [27]:
# 任务，已知c求得a，b（逆运算）
print(*c)
a, b = tuple(zip(*c))
b = list(b)
print("a={}; b={};".format(a, b))

(1, 'a') (2, 'b') (3, 'c')
a=(1, 2, 3); b=['a', 'b', 'c'];


In [28]:
# 2. 作为函数(function)的动态参数传递方法
def sum_nums(a, b, c):
    return a+b+c

sum_nums(*[1,2,3])
# 可以用作按照位置顺序的参数输入

6

In [35]:
d1 = {'a': 1,
     'b': 2,
     'c': 3}

print(sum_nums(*d1)) # 注意，一般我们默认dict不一定保留顺序，虽然Python中key的顺序一般不会改变
print(sum_nums(**d1))
# 按照函数名传递参数

abc
6


In [36]:
d2 = {'a': 1, 'b': 2, 'c': 3, 'e':100} # sum_nums中不存在的‘e’参数，报错
print(sum_nums(**d2))

TypeError: sum_nums() got an unexpected keyword argument 'e'

In [58]:
# 函数本身可以定义数量不定的参数
# 下面函数完成记录运算时间的任务
import time
def timer(my_func, *args, **kwargs):
    t0 = time.time()
    for i in range(int(1e6)):
        my_func(*args, **kwargs)
    t1 = time.time()
    print("计算100万次{}函数用时为:{:.4f}秒".format(my_func.__name__, t1-t0) )
    
def power_nums(a, b, c):
    return a**b**c  # a^(b^(c))

In [59]:
timer(power_nums, **d1)
# 这在程序中称为闭包，使用一个函数a包裹函数b，函数b完成同样的内容，而函数a在b的基础上完成额外的内容，如记录时间/写log/Flask网页后端地址导航等
# 在Python中，“@”语法糖符号是这种闭包模式的类似的简化语法

计算100万次power_nums函数用时为:0.5677秒


In [61]:
# 修时器/语法糖的用法（补充内容，本视频不要求）
def my_decorator(my_func):
    def timer(*args, **kwargs):
        t0 = time.time()
        for i in range(int(1e6)):
            my_func(*args, **kwargs)
        t1 = time.time()
        print("计算100万次{}函数用时为:{:.4f}秒".format(my_func.__name__, t1-t0) )
    return timer

@my_decorator
def power_nums(a, b, c):
    return a**b**c

power_nums(**{'a': 2, 'b': 3, 'c': 5})

计算100万次power_nums函数用时为:0.8148秒


In [ ]:
# 规则：positional arguments必须在keyword argument之前



In [ ]:
# 实际项目中如何应用动态传递参数？（例子）
# matplotlib